README自動生成スクリプトにフォルダのリンクを生成するコードを追加
SAWARATSUKI/ServiceLogos pull request #480
Opened 2024-04-27 03:17 UTC by radian462

## Description
#468 で作成されたREADME自動生成スクリプトにフォルダのリンクを生成するコードを追加しました

Added code to generate folder links to the README auto-generation script created in #468

## Checklist

- [x] I have tested the changes/updates before submitting this pull request.

2024-04-27 22:37 UTC, T-taku approved these changes

2024-04-27 23:08 UTC, lgc2333 commented
#529 did this

2024-04-28 01:13 UTC, radian462 commented
Conflict resolved.

2024-04-28 08:55 UTC, sweetliquid requested changes

2024-04-28 08:55 UTC, sweetliquid commented on docs/README-es.md
> -| Nombre           | Imagen
`Nombre` and `Imagen` is right in Spanish.

2024-04-29 04:22 UTC, closed without merging