Auto release when image changes
SAWARATSUKI/ServiceLogos pull request #631
Opened 2024-04-30 13:35 UTC by lgc2333

# Pull Request

## Description

[Please include a brief description of the changes or features you are proposing.]

## Related Issues

- #378 
- #616 

## Pictures (if applicable)

[Include any pictures that help demonstrate the changes.]

## Checklist

- [x] I have tested the changes/updates before submitting this pull request.

## Additional Notes

[Add any additional notes or context about the changes here.]

2024-04-30 14:38 UTC, lgc2333 commented
i am not familiar with bash, i'll write a python script to generate release message, wait me sometime

2024-04-30 15:28 UTC, lgc2333 commented
okay for merge
i'm tired, i'll go sleep now
good night~~~~~~

2024-04-30 16:28 UTC, VVsxmja commented on docs/scripts/generate-changelog.py
> +    # print(out)
delete this line 🤔

2024-04-30 16:55 UTC, VVsxmja requested changes

2024-04-30 16:55 UTC, VVsxmja commented on docs/scripts/generate-changelog.py
> +    # print(out)
This line should be deleted. 🤔

2024-04-30 16:55 UTC, VVsxmja commented on docs/scripts/generate-changelog.py
> +    Path("changelog.md").write_text(changelog, "u8")
`u8` is an alias. `utf_8` should be better. [Reference](https://docs.python.org/3/library/codecs.html#standard-encodings)

2024-04-30 16:55 UTC, VVsxmja commented on .github/workflows/auto-release.yml
> +      - name: Run Commands
I think it should be better to provide a descriptive name here, such as `Generate Changelog`.

2024-04-30 23:14 UTC, lgc2333 commented on docs/scripts/generate-changelog.py
> +    Path("changelog.md").write_text(changelog, "u8")
different person has different code styles, i'll keep this

2024-05-01 02:47 UTC, T-taku approved these changes
lgtm;)

2024-05-01 02:48 UTC, merged